### ISSUE TITLE
Container does not start with docker-compose when SNMP nodes are used

### ISSUE THREAD

**Issue by torevg** [aheimsbakk/container-munin#9]
Hi,

I am trying the container with a docker-compose file as below.
When I put the SNMP_NODES in comment, the container starts without any problems.
However when  I would try to use the SNMP_nodes, the container seems to stop somewhere.
Maybe I made a mistake somewhere, but I don't see it.
Can somebody see what the mistake is ?

Kind regards

Tore

```
version: "3"

services:
  munin-server:
    container_name: "munin-server"
    image: aheimsbakk/munin-alpine
    restart: unless-stopped
    ports:
      - 10.10.10.10:19950:80
    environment:
      NODES: BEERNETWORK;server1:10.10.10.20 BEERNETWORK;server2:10.10.10.30
      SNMP_NODES: routers;10.10.33.1:public routers;10.10.34.1:public routers;10.10.35.1:public routers;10.10.10.36:public
      TZ: Europe/Brussels
    volumes:
      - /opt/lowcode/docker/munin-server/etc/munin/munin-conf.d:/etc/munin/munin-conf.d 
      - /opt/lowcode/docker/munin-server/etc/munin/plugin-conf.d:/etc/munin/plugin-conf.d 
      - /opt/lowcode/docker/munin-server/var/lib/munin:/var/lib/munin 
      - /opt/lowcode/docker/munin-server/var/log/munin:/var/log/munin 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.munin-server.rule=Host(`mymunin.myhost.mydomain`)"
      - "traefik.http.routers.munin-server.entrypoints=web,websecure"
      - "traefik.http.routers.munin-server.tls=true"
    networks:
      - traefik-stack_default

networks:
      traefik-stack_default:
        external: true 
```
